name: loyalty
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scan: ^1.4.3
  pin_code_fields: ^7.2.0
  adaptive_theme: ^2.2.0
  introduction_screen: ^2.1.0
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.0+1"
  firebase_analytics: "^7.0.1"
  cloud_firestore: "^0.16.0"
  url_launcher:
  select_form_field:
  carousel_slider:
  rate_my_app:
  #permission_handler:
  firebase_messaging:
  pin_code_view:
  firebase_dynamic_links: ^0.8.0
  flutter_bloc: ^7.0.0
  provider:
  sms_autofill:
  flutter_webview_plugin:
  flutter_html:
  http:
  qrscan:
  shared_preferences:
  flutter_email_sender:
  connectivity:
  share:
  get:
  pinput: ^1.2.0
  flutter_spinkit: "^4.1.2"
  equatable: ^2.0.0
  photo_view: ^0.11.1
  flutter_localizations:
    sdk: flutter
  path_provider:
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  firebase_core: ^1.0.0
  firebase_core_web: ^0.2.1+3
  firebase_core_platform_interface: ^4.0.0
  cloud_firestore_platform_interface: ^3.0.2
  plugin_platform_interface: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/localization/langs/am.json
    - lib/localization/langs/ru.json
    - lib/localization/langs/en.json
    - assets/onboarding_0.jpg
    - assets/onboarding_1.jpg
    - assets/onboarding_2.jpg
    - assets/new_card_added.webp
    - assets/male.jpg
    - assets/female.jpg
    - assets/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf